"""
Public Stats Router — White-label publisher statistics page.

No authentication required. Access is controlled by a signed token
that encodes the publisher ID. The token is generated by admin via
POST /direct-links/generate-stats-token.

Token format (base64): {publisher_id}:{email}:{unix_timestamp}
The publisher_id in the path must match the one in the token.

No internal branding, campaign names, domain names, or admin info
is exposed — only aggregated performance numbers.
"""
from fastapi import APIRouter, HTTPException, Query, Depends
from datetime import datetime, timedelta
import base64
import logging

from app.dependencies import get_db

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/public-stats", tags=["Public Stats"])


def _validate_token(token: str, publisher_id: str) -> bool:
    """
    Validate the stats access token.
    Token is urlsafe_base64( publisher_id:email:timestamp ) with padding stripped.
    Returns True if the publisher_id in the token matches the URL parameter.
    """
    try:
        # Restore stripped padding
        padded = token + "=" * (4 - len(token) % 4) if len(token) % 4 else token
        decoded = base64.urlsafe_b64decode(padded).decode("utf-8")
        parts = decoded.split(":")
        if len(parts) < 1:
            return False
        return parts[0] == publisher_id
    except Exception:
        return False


@router.get("/{publisher_id}")
async def get_publisher_public_stats(
    publisher_id: str,
    token: str = Query(..., description="Access token from admin panel"),
    days: int = Query(30, ge=1, le=90, description="Number of days to include"),
    db=Depends(get_db),
):
    """
    Get white-label publisher statistics.
    Called by the /public-stats/[publisherId] Next.js page.
    No admin branding exposed — returns only aggregated performance data.
    """
    # ── Token validation ──────────────────────────────────────────────────────
    if not _validate_token(token, publisher_id):
        raise HTTPException(status_code=403, detail="Invalid or expired access link")

    # ── Publisher lookup ──────────────────────────────────────────────────────
    from bson import ObjectId
    try:
        pub_oid = ObjectId(publisher_id)
    except Exception:
        raise HTTPException(status_code=404, detail="Not found")

    publisher = await db.publishers.find_one({"_id": pub_oid, "role": "publisher"})
    if not publisher:
        raise HTTPException(status_code=404, detail="Not found")

    # ── Date range ────────────────────────────────────────────────────────────
    end_date = datetime.utcnow()
    start_date = end_date - timedelta(days=days)

    # ── Aggregate clicks ──────────────────────────────────────────────────────
    # clicks collection uses "publisher_id" as string ObjectId, "timestamp" field,
    # and "os" for operating system, "status" for valid/invalid/pending
    click_match = {
        "publisher_id": publisher_id,
        "timestamp": {"$gte": start_date, "$lte": end_date},
    }

    # Total clicks breakdown by OS
    os_pipeline = [
        {"$match": click_match},
        {"$group": {
            "_id": "$os",
            "count": {"$sum": 1},
        }},
    ]
    os_results = await db.clicks.aggregate(os_pipeline).to_list(length=None)

    total_clicks = 0
    windows_clicks = 0
    mac_clicks = 0
    for row in os_results:
        os_val = (row.get("_id") or "").lower()
        cnt = row.get("count", 0)
        total_clicks += cnt
        if any(w in os_val for w in ("windows", "win")):
            windows_clicks += cnt
        elif any(m in os_val for m in ("mac", "ios", "darwin", "macos")):
            mac_clicks += cnt

    # ── Aggregate direct link conversions ─────────────────────────────────────
    conv_match = {
        "publisher_id": publisher_id,
        "created_at": {"$gte": start_date, "$lte": end_date},
    }
    conv_result = await db.direct_link_events.count_documents(conv_match)
    total_conversions = conv_result

    conversion_rate = (total_conversions / total_clicks * 100) if total_clicks > 0 else 0.0

    # ── Daily breakdown ───────────────────────────────────────────────────────
    daily_clicks_pipeline = [
        {"$match": click_match},
        {"$group": {
            "_id": {"$dateToString": {"format": "%Y-%m-%d", "date": "$timestamp"}},
            "clicks": {"$sum": 1},
            "windows_clicks": {"$sum": {"$cond": [
                {"$regexMatch": {"input": {"$ifNull": ["$os", ""]}, "regex": "windows|win", "options": "i"}},
                1, 0,
            ]}},
            "mac_clicks": {"$sum": {"$cond": [
                {"$regexMatch": {"input": {"$ifNull": ["$os", ""]}, "regex": "mac|ios|darwin", "options": "i"}},
                1, 0,
            ]}},
        }},
        {"$sort": {"_id": -1}},
        {"$limit": days},
    ]
    daily_clicks_raw = await db.clicks.aggregate(daily_clicks_pipeline).to_list(length=None)

    # Daily conversions
    daily_conv_pipeline = [
        {"$match": conv_match},
        {"$group": {
            "_id": {"$dateToString": {"format": "%Y-%m-%d", "date": "$created_at"}},
            "conversions": {"$sum": 1},
        }},
    ]
    daily_conv_raw = await db.direct_link_events.aggregate(daily_conv_pipeline).to_list(length=None)
    daily_conv_map = {row["_id"]: row["conversions"] for row in daily_conv_raw}

    daily_breakdown = []
    for row in daily_clicks_raw:
        date_str = row["_id"]
        clicks = row["clicks"]
        conversions = daily_conv_map.get(date_str, 0)
        cr = round(conversions / clicks * 100, 2) if clicks > 0 else 0.0
        daily_breakdown.append({
            "date": date_str,
            "clicks": clicks,
            "conversions": conversions,
            "cr": cr,
            "windows_clicks": row.get("windows_clicks", 0),
            "mac_clicks": row.get("mac_clicks", 0),
        })

    # ── Insights ──────────────────────────────────────────────────────────────
    avg_daily_clicks = round(total_clicks / days) if days > 0 else 0

    # Trend: compare last 7 days vs prior 7 days
    trend = "stable"
    if len(daily_breakdown) >= 14:
        recent_avg = sum(d["clicks"] for d in daily_breakdown[:7]) / 7
        older_avg = sum(d["clicks"] for d in daily_breakdown[7:14]) / 7
        if recent_avg > older_avg * 1.1:
            trend = "up"
        elif recent_avg < older_avg * 0.9:
            trend = "down"

    # Platform preference
    windows_ratio = windows_clicks / total_clicks if total_clicks > 0 else 0.5
    if windows_ratio > 0.65:
        platform_preference = "windows"
    elif windows_ratio < 0.35:
        platform_preference = "mac"
    else:
        platform_preference = "balanced"

    # Performance score
    if conversion_rate >= 6:
        performance_score = "Excellent"
    elif conversion_rate >= 4:
        performance_score = "Good"
    elif conversion_rate >= 2:
        performance_score = "Average"
    else:
        performance_score = "Building"

    # Top performance day
    top_day = max(daily_breakdown, key=lambda x: x["cr"], default=None)

    return {
        "success": True,
        "data": {
            "publisher_name": publisher.get("name", "Publisher"),
            "publisher_id": publisher_id,
            "date_range": f"Last {days} Days",
            "total_impressions": total_clicks,
            "unique_windows_clicks": windows_clicks,
            "unique_mac_clicks": mac_clicks,
            "total_conversions": total_conversions,
            "conversion_rate": round(conversion_rate, 2),
            "performance_score": performance_score,
            "daily_breakdown": daily_breakdown,
            "insights": {
                "top_performance_day": top_day["date"] if top_day else None,
                "avg_daily_clicks": avg_daily_clicks,
                "trend_direction": trend,
                "platform_preference": platform_preference,
            },
        },
    }
